-- MySQL 8.0 schema for admin-base
-- Notes:
-- - IDs are generated by application (MyBatis-Plus IdType.ASSIGN_ID), so no AUTO_INCREMENT.
-- - Soft delete uses `deleted` (0/1). Unique keys are global and do not allow reuse after delete.

SET NAMES utf8mb4;

CREATE TABLE sys_user (
  id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  email VARCHAR(128) DEFAULT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  avatar_file_id BIGINT DEFAULT NULL COMMENT 'sys_file.id (avatar)',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_username (username),
  KEY idx_sys_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_role (
  id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_permission (
  id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL COMMENT 'e.g. user:create',
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_permission_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_user_role (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_role (user_id, role_id),
  KEY idx_sys_user_role_user_id (user_id),
  KEY idx_sys_user_role_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_role_permission (
  id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_permission (role_id, permission_id),
  KEY idx_sys_role_permission_role_id (role_id),
  KEY idx_sys_role_permission_permission_id (permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_file (
  id BIGINT NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  stored_name VARCHAR(255) NOT NULL,
  path VARCHAR(512) NOT NULL COMMENT 'relative path on disk',
  size BIGINT NOT NULL,
  content_type VARCHAR(128) DEFAULT NULL,
  visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE' COMMENT 'PUBLIC/PRIVATE',
  user_id BIGINT NOT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_file_path (path),
  KEY idx_sys_file_user_id (user_id),
  KEY idx_sys_file_visibility (visibility)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_notification (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  type VARCHAR(32) NOT NULL COMMENT 'SYSTEM/BUSINESS/ANNOUNCEMENT',
  is_read TINYINT NOT NULL DEFAULT 0 COMMENT '0-unread 1-read',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sys_notification_user_created (user_id, created_at),
  KEY idx_sys_notification_user_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_message (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  contact_email VARCHAR(128) NOT NULL COMMENT 'contact email',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0-pending 1-replied',
  reply_content TEXT DEFAULT NULL,
  replied_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sys_message_user_created (user_id, created_at),
  KEY idx_sys_message_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_banner (
  id BIGINT NOT NULL,
  title VARCHAR(128) DEFAULT NULL,
  image_file_id BIGINT NOT NULL COMMENT 'sys_file.id (PUBLIC)',
  link_url VARCHAR(512) DEFAULT NULL,
  sort_no INT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_banner_enabled_sort (enabled, sort_no),
  KEY idx_biz_banner_image_file_id (image_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_activity (
  id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  cover_file_id BIGINT NOT NULL COMMENT 'sys_file.id (PUBLIC)',
  content TEXT NOT NULL COMMENT 'HTML',
  address VARCHAR(255) DEFAULT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  signup_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  donate_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  max_participants INT DEFAULT NULL,
  donation_target DECIMAL(12,2) DEFAULT NULL,
  donated_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_activity_enabled_time (enabled, start_time, end_time),
  KEY idx_biz_activity_cover_file_id (cover_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_activity_signup (
  id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL COMMENT 'SIGNED/CANCELED/CHECKED_IN',
  signed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  canceled_at DATETIME DEFAULT NULL,
  checked_in_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_biz_activity_signup (activity_id, user_id),
  KEY idx_biz_activity_signup_activity_id (activity_id),
  KEY idx_biz_activity_signup_user_id (user_id),
  KEY idx_biz_activity_signup_signed_at (signed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_activity_donation (
  id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_activity_donation_activity_id (activity_id),
  KEY idx_biz_activity_donation_user_id (user_id),
  KEY idx_biz_activity_donation_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_activity_favorite (
  id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_biz_activity_favorite (activity_id, user_id),
  KEY idx_biz_activity_favorite_activity_id (activity_id),
  KEY idx_biz_activity_favorite_user_id (user_id),
  KEY idx_biz_activity_favorite_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_crowdfunding_project (
  id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  cover_file_id BIGINT NOT NULL COMMENT 'sys_file.id (PUBLIC)',
  content TEXT NOT NULL COMMENT 'HTML',
  target_amount DECIMAL(12,2) NOT NULL,
  raised_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  start_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time DATETIME NOT NULL,
  status VARCHAR(16) NOT NULL COMMENT 'PENDING/APPROVED/REJECTED',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_cf_project_status_end_time (status, end_time),
  KEY idx_biz_cf_project_created_by (created_by),
  KEY idx_biz_cf_project_cover_file_id (cover_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_crowdfunding_donation (
  id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  is_anonymous TINYINT NOT NULL DEFAULT 0 COMMENT '0-no 1-yes',
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_cf_donation_project_id (project_id),
  KEY idx_biz_cf_donation_user_id (user_id),
  KEY idx_biz_cf_donation_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_story (
  id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  cover_file_id BIGINT NOT NULL COMMENT 'sys_file.id (PUBLIC)',
  content TEXT NOT NULL COMMENT 'HTML',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_story_enabled_created_at (enabled, created_at),
  KEY idx_biz_story_cover_file_id (cover_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_comment (
  id BIGINT NOT NULL,
  target_type VARCHAR(16) NOT NULL COMMENT 'STORY',
  target_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_comment_target_created_at (target_type, target_id, created_at),
  KEY idx_biz_comment_user_created_at (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
