-- MySQL 8.0 schema for admin-base
-- Notes:
-- - IDs are generated by application (MyBatis-Plus IdType.ASSIGN_ID), so no AUTO_INCREMENT.
-- - Soft delete uses `deleted` (0/1). Unique keys are global and do not allow reuse after delete.

SET NAMES utf8mb4;

CREATE TABLE sys_user (
  id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  email VARCHAR(128) DEFAULT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  avatar_file_id BIGINT DEFAULT NULL COMMENT 'sys_file.id (avatar)',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_username (username),
  KEY idx_sys_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_role (
  id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_permission (
  id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL COMMENT 'e.g. user:create',
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_permission_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_user_role (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_role (user_id, role_id),
  KEY idx_sys_user_role_user_id (user_id),
  KEY idx_sys_user_role_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_role_permission (
  id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_permission (role_id, permission_id),
  KEY idx_sys_role_permission_role_id (role_id),
  KEY idx_sys_role_permission_permission_id (permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_file (
  id BIGINT NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  stored_name VARCHAR(255) NOT NULL,
  path VARCHAR(512) NOT NULL COMMENT 'relative path on disk',
  size BIGINT NOT NULL,
  content_type VARCHAR(128) DEFAULT NULL,
  visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE' COMMENT 'PUBLIC/PRIVATE',
  user_id BIGINT NOT NULL,
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_file_path (path),
  KEY idx_sys_file_user_id (user_id),
  KEY idx_sys_file_visibility (visibility)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_notification (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  type VARCHAR(32) NOT NULL COMMENT 'SYSTEM/BUSINESS/ANNOUNCEMENT',
  is_read TINYINT NOT NULL DEFAULT 0 COMMENT '0-unread 1-read',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sys_notification_user_created (user_id, created_at),
  KEY idx_sys_notification_user_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_message (
  id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  contact_email VARCHAR(128) NOT NULL COMMENT 'contact email',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0-pending 1-replied',
  reply_content TEXT DEFAULT NULL,
  replied_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sys_message_user_created (user_id, created_at),
  KEY idx_sys_message_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE biz_banner (
  id BIGINT NOT NULL,
  title VARCHAR(128) DEFAULT NULL,
  image_file_id BIGINT NOT NULL COMMENT 'sys_file.id (PUBLIC)',
  link_url VARCHAR(512) DEFAULT NULL,
  sort_no INT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0-normal 1-deleted',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_biz_banner_enabled_sort (enabled, sort_no),
  KEY idx_biz_banner_image_file_id (image_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
